
4fs_apokasc_training_set_lrs[SNR=250,4800<Teff<9999]    4fs_apokasc_test_set_lrs[4900<Teff<9999]    ../output_data/cannon_quick    1e-4

4fs_apokasc_training_set_lrs[SNR=250]    4fs_apokasc_test_set_lrs    ../output_data/cannon_apokasc_lrs    1e-4
# 4fs_apokasc_training_set_lrs_snrperband[SNR=250]    4fs_apokasc_test_set_lrs_snrperband    ../output_data/cannon_apokasc_lrs_snrperband    1e-4
# 4fs_apokasc_training_set_lrs_snrperband_noblue[SNR=250]    4fs_apokasc_test_set_lrs_snrperband_noblue    ../output_data/cannon_apokasc_lrs_snrperband_noblue    1e-4

4fs_apokasc_training_set_hrs[SNR=250]    4fs_apokasc_test_set_hrs    ../output_data/cannon_apokasc_hrs    1e-4
# 4fs_apokasc_training_set_hrs_snrperband[SNR=250]    4fs_apokasc_test_set_hrs_snrperband    ../output_data/cannon_apokasc_hrs_snrperband    1e-4
# 4fs_apokasc_training_set_hrs_snrperband_noblue[SNR=250]    4fs_apokasc_test_set_hrs_snrperband_noblue    ../output_data/cannon_apokasc_hrs_snrperband_noblue    1e-4

4fs_ahm2017_sample_hrs[SNR=250]    4fs_ahm2017_perturbed_hrs    ../output_data/cannon_ahm2017_perturbed_hrs    1e-4
4fs_ahm2017_sample_lrs[SNR=250]    4fs_ahm2017_perturbed_lrs    ../output_data/cannon_ahm2017_perturbed_lrs    1e-4

4fs_ges_dwarf_sample_hrs[SNR=250]    4fs_ges_dwarfs_perturbed_hrs    ../output_data/cannon_ges_dwarfs_perturbed_hrs    1e-4
4fs_ges_dwarf_sample_lrs[SNR=250]    4fs_ges_dwarfs_perturbed_lrs    ../output_data/cannon_ges_dwarfs_perturbed_lrs    1e-4

4fs_ges_marcs_grid_hrs[SNR=250]    4fs_ahm2017_perturbed_hrs    ../output_data/cannon_marcs_ahm2017_hrs    1e-4
4fs_ges_marcs_grid_lrs[SNR=250]    4fs_ahm2017_perturbed_lrs    ../output_data/cannon_marcs_ahm2017_lrs    1e-4

